### ISSUE TITLE
AttributeError: 'Optimizer' object has no attribute 'threadExecutor'

### ISSUE THREAD

**Issue by TheBeeGuy** [electricbrainio/hypermax#6]
I'm not sure what info I need to provide for this, but I'm getting some errors when I try to run hypermax. I have LightGBM installed (Version 2.2.3) and OpenMP (libomp stable 8.0.1) installed succefully using homebrew. It throws warnings for libomp and lightGBM, and then AttributeError: 'Optimizer' object has no attribute 'threadExecutor' 

Please let me know if I need to provide anything else. Any guidance would be appreciated!

I'm on macOS Mojave: Version 10.14.6

(venv)$ hypermax xgb_search.json 
/usr/local/lib/python3.7/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/hypermax", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/hypermax/cli.py", line 21, in main
    optimizer = Optimizer(config_data)
  File "/usr/local/lib/python3.7/site-packages/hypermax/optimizer.py", line 51, in __init__
    self.space = self.config.createHyperparameterSpace()
  File "/usr/local/lib/python3.7/site-packages/hypermax/configuration.py", line 13, in createHyperparameterSpace
    space = param.createHyperoptSpace(lockedValues)
  File "/usr/local/lib/python3.7/site-packages/hypermax/hyperparameter.py", line 52, in createHyperoptSpace
    space[key] = Hyperparameter(config, self, name + "." + key).createHyperoptSpace(lockedValues)
  File "/usr/local/lib/python3.7/site-packages/hypermax/hyperparameter.py", line 75, in createHyperoptSpace
    return hp.loguniform(name, math.log(min), math.log(max))
ValueError: math domain error
Exception ignored in: <function Optimizer.__del__ at 0x118c6fb00>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hypermax/optimizer.py", line 85, in __del__
    if self.threadExecutor:
AttributeError: 'Optimizer' object has no attribute 'threadExecutor'

**Comment by genixpro** [comment]
This is a pretty unusual error - this would imply some sort of timing or
thread issue. It must be specific to your machine. Would you be willing to
help me diagnose the issue? I'll need you to put in a few diagnostics to
figure out whats happening.

------
Bradley Arsenault < bradley.allen.arsenault@gmail.com >
647-261-0462
Toronto, Ontario

**Comment by TheBeeGuy** [comment]
That would be great. Please let me know what I should do. Thanks very much

**Comment by genixpro** [comment]
Oh I think I might know the issue. Can you paste your Hyperparameter space
to me?

It might be that you have a log-scale hyperparameter set with a minimum of
0. You can't have log-scale hyperparameters with a minimum of 0 - the log
of 0 is undefined.
------
Bradley Arsenault < bradley.allen.arsenault@gmail.com >
647-261-0462
Toronto, Ontario
